# .upptimerc.yml

owner: aalaraj-biotrack      # ← your GitHub org/user
repo: status-page            # ← this repo name

sites:
  - name: arstems-arkansas-gov
    url: https://arstems.arkansas.gov
  - name: mmj-adh-arkansas-gov
    url: https://mmj.adh.arkansas.gov
  - name: arstems-security-tags
    url: https://arstems.arkansas.gov/security-tags/
  - name: transport-ar-biotrackthc-net
    url: https://transport.ar.biotrackthc.net
  - name: server-biotrackthc-net
    url: https://server.biotrackthc.net
  - name: mcmonitoring-agr-illinois-gov
    url: https://mcmonitoring.agr.illinois.gov
  - name: il-uat01-biotrackthc-net
    url: https://il-uat01.biotrackthc.net
  - name: uat-api-licensee-fl-biotr-ac-heartbeat
    url: https://uat.api.licensee.fl.biotr.ac/heartbeat
  - name: qa-api-licensee-fl-biotr-ac-heartbeat
    url: https://qa.api.licensee.fl.biotr.ac/heartbeat
  - name: mcp-tracking-nmhealth-org
    url: https://mcp-tracking.nmhealth.org
  - name: mcp-patient-tracking-nmhealth-org
    url: https://mcp-patient-tracking.nmhealth.org
  - name: hicsts-hawaii-gov
    url: https://hicsts.hawaii.gov
  - name: mmp-sts-cannabis-ny-gov
    url: https://mmp-sts.cannabis.ny.gov
  - name: delaware-biotrackthc-net
    url: https://delaware.biotrackthc.net
  - name: delaware-biotrackthc-patients
    url: https://delaware.biotrackthc.net/patients/
  - name: cannabispr-biotrackthc-net
    url: https://cannabispr.biotrackthc.net
  - name: mminventory-health-nd-gov
    url: https://mminventory.health.nd.gov
  - name: mmregistration-health-nd-gov
    url: https://mmregistration.health.nd.gov
  - name: ndtags-biotrackthc-com
    url: https://ndtags.biotrackthc.com
  - name: nhcannabisregistry-biotrackthc-com
    url: https://nhcannabisregistry.biotrackthc.com
  - name: patients-va-biotr-ac
    url: https://patients.va.biotr.ac
  - name: products-va-biotr-ac
    url: https://products.va.biotr.ac
  - name: wm01-biotrackthc-net
    url: https://wm01.biotrackthc.net
  - name: trace-ct-biotr-ac
    url: https://trace.ct.biotr.ac

status-website:
  # If you own a custom domain, uncomment & set `cname:`; otherwise leave baseUrl
  # cname: status.your-domain.com
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: BioTrack Status
  introTitle: "BioTrack Service Status"
  introMessage: >-
    This status page tracks uptime for all BioTrack endpoints.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/aalaraj-biotrack/status-page

# — notifications, assign-to, custom checks, etc. go here —
# see https://upptime.js.org/docs/configuration
